datproject/dat-node

- index.js
- readme.md
fixes https://github.com/datproject/dat/issues/521
> ignore hidden by default

- index.js
- tests/misc.js
I think this should do it. (I’ve also updated the test with a few new edge cases)
Thanks :)
closes: #5
> simplify default ignore pattern

- CHANGELOG.md
- index.js
- package.json
- readme.md
- tests/download.js
* Uses new functions in hyperdrive 7.5 to measure download progress in blocks not bytes
* Improves file count by checking for duplicates
> Improve download stats

- index.js
- tests/misc.js
#32, #33, #34 
cc @juliangruber
> expose key, owner, peers

- index.js
- package.json
- tests/misc.js
- tests/share.js
Upgrade hyperdrive-archive-swarm to v5 which removes webrtc support.
> upgrade swarm and remove webrtc

- lib/stats.js
- package.json
waiting on https://github.com/joehand/dat-folder-archive/pull/1 and dat-encoding bug release to 4.0.1
> use dat-encoding 4

- lib/import-files.js
https://github.com/juliangruber/hyperdrive-import-files/pull/36
> add indexing to import

- dat.js
- tests/misc.js
RE: https://github.com/datproject/dat-desktop/pull/173. 
Hopefully closes #84 and definitely closes #85
> Fix close issues with dat-desktop

- index.js
changes the dir stuff around, think it fixes the opts casting bug. Also makes errors more transparent (which is useful if we're 4 layers deep into the wrapper stuff)
> fix options casting

- lib/init-archive.js
- tests/misc.js
> improve key handle and moar debug = more fun

- readme.md
Goal: get more of the docs in a single place so we don't have to search docs from all the other modules. #87
> WIP: add docs about options/properies of sub modules

- lib/init-archive.js
Reverts datproject/dat-node#95
> Revert "do not set length if we own it"

- dat.js
- test/misc.js
* Error for two closes sync (before only erred after first closed called back)
* Add two close test sync
> Error on close twice sync

- package.json
- test/download.js
Add test for #105 . Fix is in hyperdrive, open pr: https://github.com/mafintosh/hyperdrive/pull/128
Will wait to merge until hyperdrive PR is fixed so we can run tests again.
> Add failing sparse test

- index.js
- test/options.js
`errorIfExists` option wasn't working. 
* Add test that would have caught this.
> fix error if exists

- index.js
- lib/storage.js
- package.json
- readme.md
Changes defaults to use the `dat-storage` module.
> Use Dat storage module

- index.js
- lib/storage.js
- test/download.js
- test/misc.js
- test/options.js
> check for metadata.key file in .dat

- index.js
- package-lock.json
- package.json
Resolve keys to support http hosted dat links #152
> resolve http dat links

- test/download.js
> add test for closing a dat and network

- dat.js
- package-lock.json
- package.json
- test/misc.js
Hypercore introduced errors that might occur if something is read while closing. When DAT closes it has become more important to close the network and file-import
before the archive is closed.
This PR makes sure that the DAT is destructed in the proper order.
> Making sure that a DAT is closed in the correct order

- dat.js
- index.js
> Change to es6 class syntax 

- readme.md
ping @joehand what do you think?
> Add note about dat SDK to README
