index.js
lib/db.js
tests/misc.js

This is fix part one for https://github.com/datproject/dat/issues/561, next we just need to print a nice error message if `/^OpenError/.test(err.message)`.

Catch LevelDB OpenErrors

---

lib/db.js

New error if user tries to download to a directory that has a different Dat:
```
Error: Destination path already exists and contains a different dat.
Please download to a new directory or remove the existing .dat folder.
```

Clarify error for existing dat in directory

---

index.js
tests/misc.js

A live archive does not have its key until opened, and this is currently not propagated back to `.key` of the Dat instance.  This breaks desktop archive creation, which does a simple open-then-close to obtain new archive key.  workaround is at https://github.com/datproject/dat-desktop/commit/cfb3d6cb46e3ab9ca27c7021258a4abd454903bb

populate key after archive opened

---

dat.js

As per the conversation in irc, this improves on the usability of keys provided on Dat's which actually originate on archive instances.

Move properties from dat.archive to getters

---

CHANGELOG.md
dat.js
index.js
lib/import-files.js
lib/init-archive.js
lib/network.js
lib/stats.js
package.json
readme.md
tests/download.js
tests/misc.js
tests/share.js

I think I finished this before the break but need to check it over. ~Depends on https://github.com/joehand/dat-folder-archive/pull/2.~ (Implemented this directly in here instead of in dat-folder-archive).
I changed the API slightly around the network to make it easier to use an external swarm module. But everything is still backwards compatible.
* Not doing: ~Release MD support in dat-folder-archiver~
* Done: ~Add MD test here~
* Done: ~pfrazee: updating the usage to simplify it, so you can just do `Dat(drive, function(err, dat) {}`~
* [Done](https://github.com/datproject/dat-node/pull/65#issuecomment-272560931)  ~Ensure compatibility with dat cli (to do this we need to put the archive key into the `.dat` db)~

Multidrive support

---

dat.js
lib/import-files.js
lib/stats.js
package.json

Working on some bugs for https://github.com/datproject/dat-node/milestone/3
* Close network & file watcher before archive/db #71 
* Use discovery key for subleveldb's (fewer public keys hanging around)
* Improve counting speed (part of #75)

Fixing bugs for dat-next

---

index.js
package.json

When writing `multidat` I noticed the input args were being mutated; this fixes that. Thanks!

don't mutate input args

---

lib/init-archive.js
tests/misc.js

* Mostly cosmetic changes to be more explicit in the logic. 
* Also cast keys as strings to [check if they match](https://github.com/datproject/dat-node/compare/key-logic?expand=1#diff-98e4832c20ce3f02021e173f43d0f8a5R83)
* Add some asserts before `tryOpen` to make sure we got it correct.

more explicit handling of keys

---

dat.js
lib/init-archive.js
package.json

Source files were getting corrupted from bad replication. This ensures we do not ever download data, possibly corrupting the source. This fix should also be covered in hypercore v4.19.4 (which is covered in our dependency range).
We added an `opts.length` to the `raf` function call to fix replication for new files that were shorter than old versions. Unfortunately, because of bad replication we are getting files truncated now. There may also be other bugs related to this, so am removing for now.
This may/may not be a bug fix. The do not download should cover this. But we do not use `archive.append` in importer, so do not need the file option
I pinned it to 7.13.2. I'm not sure the recent updates caused the bugs but they may have exposed an old replication bug.

Temporary fixes for some critical replication issues.

---

lib/init-archive.js
package.json

Rolls back some temporary changes from #100. 
`opts.length` is safe to pass because of the bug fixed in hypercore. We may still truncate files in weird situations but less worried about it now because truncation will not be the default.
Can get back on latest hyperdrive. It was breaking files before because of the `_selectLatest` code exposing the hypercore bug.

add back opts.length and upgrade hypdrive again

---

lib/init-archive.js

Fixes intermittent archive read verification errors on the source. The content was using the wrong key prefix when trying to read. 
Couldn't really figure out what was causing this (something about the bad content feed being used in new archive), but this fixes it for now.

close old archive before opening new

---

lib/init-archive.js

* Make a copy of the opts to pass to `createArchive`. 
* Set `opts.file` instead of setting to `null`. Test coverage showed me that wasn't working =).

handle archive opts better and set file for owner

---

lib/init-archive.js
test/options.js

Previously `createIfMissing` would only check if there was a `.dat` folder. This passes that option to level so it'll error if there is a `.dat` folder but the database is missing.

createIfMissing errors for empty .dat folder, closes #109

---

dat.js
test/download.js
test/importing.js
test/share.js

Previously, the import callback auto finalized snapshot archives. This was a bit too fancy and would only allow for a single import to snapshot archives.
* Remove too fancy auto finalize
* Do not require callback for import options (will emit errors if callback is null) #108 
* Fix snapshot tests
* Add import without callback test

Cleanup import callback issues, closes #108

---

dat.js
lib/import-files.js
readme.md
test/importing.js

* Adds support for a `.datignore` file, #117 
Notes: the `.datignore` file itself will be ignore right now by default with `opts.ignoreHidden`.
TODO:
* ~Add test(s) for dat ignore file~
* ~Docs docs docs 📖 ~

add .datignore to import ignore

---

dat.js
readme.md
test/download.js

Adds `dat.pause()` and `dat.resume()`, #69 . Right now this is just a alias for `join` and `leave`. Tried to use unprioritize but was having some issues with how hyperdrive forces downloads right now.
Also fix some bugs in the `join` * `leave` code. This makes the leave a bit more strict including destroying the swarm. There were still some messages getting through (protocol bug?) if I only left the swarm on the key, this may have been from duplicate connections.

WIP: add pause/resume and improve network join/leave

---

lib/stats.js
package.json
readme.md
test/network.js

Adds a method to the stats that exposes clearer peer information.
EDIT: API Changed:
* `peers.total` - total number of connected peers
* `peers.complete` - connected peers with all the content data
* `peers.downloadingFrom` - connected peers the user has downloaded data from
---
Old stuff
```js
var stats = dat.trackStats()
var peers = stats.peers()
peers.totalPeers // total peers, from archive.content.peers
peers.activePeers // peers that have data (peer.remoteLength > 0)
peers.sendingPeers // peers that have sent data to user (peer.downloaded > 0)
peers.completePeers // peers that have the complete content feed (peer.remoteLength === archive.content.blocks)
```
This is only for **current connections**, it does not keep a cache once a peer goes offline.
| All connections | Some Content …

Improved Peer stats

---

lib/network.js
test/network.js

Pass network options to discovery swarm to allow udp, tcp, dns, dht to be set or turned off. This was a regression from removing hyperdiscovery. #125

pass through opts to discovery-swarm

---

lib/network.js
package.json

Use `dat-swarm-defaults` instead of `datland-swarm-defaults`.

use dat-swarm-defaults

---

lib/import-files.js
package.json
readme.md

Adds some basic progress stats to importer.
* `importer.indexSpeed` - importing speed
New options, `opts.count`, replaces old count stuff with better stats using a dry import run. On startup it will tell you how many files need to be imported. 
* `importer.count.files` is the number of files to be imported on startup
* `importer.putDone` can then be used to see if it is done

use dry run for import progress

---

dat.js
lib/stats.js
package.json

Updates stats API to return the following on `stats.get()`:
```js
{
version: 0,             // archive.version these stats describe
files: 0,                  // file count for this version
byteLength: 0,      // total archive byte size for version
length: 0,               // number of blocks for the files in this version
downloaded: 0      // Downloaded blocks 
}
```
Stats automatically update to latest version when available. 
`downloaded/length` should work for download progress but I need to check with mafintosh if I need to recount on clear (when local blocks are deleted).
cc @juliangruber

Add archive + download stats

---

lib/storage.js
test/misc.js

before the error would be thrown by `dat-storage` out of band

fix error propagation on invalid dat path

---

lib/import-files.js
readme.md
test/importing.js
test/share.js

Re: https://github.com/datproject/dat/issues/741#issuecomment-300489805. We don't need directories in metadata for anything cuz hyperdrive is sweet.
Directories can pollute metadata and can be confusing if mtime changes without a file inside the dat changing (e.g. if it is ignored).
PR adds `opts.ignoreDirs` to import options, default true.

ignore directories by default

---

CHANGELOG.md
lib/storage.js
package.json
readme.md

Allows using regular sleep storage in a directory by passing `dir` and setting `opts.latest = false`. This will store content as `content.data` folder so we can keep history.

use regular sleep store for not latest

---

dat.js
lib/serve.js
package-lock.json
package.json
readme.md

Adds hyperdrive-http support to dat-node baked in. Serve archive over http:
```js
Dat('dir', function (err, dat) {
dat.serveHttp(opts)
})
```

add hyperdrive-http support

---

lib/stats.js
package.json

there is still a rc where it might be >100 for a little bit depending on whether `clear` or the `diff` stream fires first. this fixes the last remaining issues though in general

fix progress bar being wrong when deletes / overwrites happen

---

index.js

I haven't managed to reproduce this in a test, but in an example where for example the secret keys don't match, this would otherwise emit an uncatchable error.
What do you think, @joehand?

catch hyperdrive open errors

---

index.js
test/share.js

Fixes issue https://github.com/datproject/dat-node/issues/149.
```dat.resume``` now returns true event if the the archive is empty by checking if the ```.dat``` folder exists.
Tests for this feature also included.

Set dat.resume to true for empty archives

---

package.json

The smallest of small prs: this fixes a typo in package.json.

fix package.json typo

---

package.json

Rolling back to `random-access-file@2.1.0` fixes #238. We can update this dependency once https://github.com/random-access-storage/random-access-file/pull/20 comes through.

Windows related issues caused by random-access-file dependency
